name: Release Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: "v0.0.0"

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update version
        id: update_version
        run: |
          RAW_TAG=${{ github.event.inputs.version }}
          NEW_VERSION="${RAW_TAG#v}"
          echo "Bumping version to $NEW_VERSION"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' manifest.json > manifest.tmp.json && mv manifest.tmp.json manifest.json
          npx -y prettier -cw .

      - uses: planetscale/ghcommit-action@v0.2.20
        with:
          commit_message: "Bump version to ${{ github.event.inputs.version }}"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Tag the release
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
